package com.actl.mvp.api.framework

import android.util.Log

object ApiModuleRegistry {
    private const val TAG = "ApiModuleRegistry"

    fun defaultModules(): List<ApiDefinition> {
        val modules = GeneratedApiRegistry.modules()
        require(modules.isNotEmpty()) { "No API modules generated by KSP under com.actl.mvp.api.*" }
        Log.i(TAG, "Loaded ${modules.size} API module(s) by KSP registry")
        return modules
    }
}
